'use strict';
// Failure injection stays in the loopback browser fixture, never in production.
const { chromium } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const url = process.env.REMOTECONTROL_BROWSER_URL;
let browser;
(async () => {
  if (!url || new URL(url).hostname !== '127.0.0.1') throw new Error('Use the local browser-review fixture.');
  browser = await chromium.launch({ channel: 'chrome', headless: true, chromiumSandbox: true });
  const page = await browser.newPage({ viewport: { width: 900, height: 690 } });
  await page.goto(url);
  await page.waitForFunction(() => window.remoteControl);
  await page.evaluate(async () => { const s = await window.remoteControl.snapshot(); if (!s.value.testMode) throw new Error('Not a fixture'); for (const d of s.value.devices) await window.remoteControl.removeDevice(d.id); });
  await page.reload();
  await page.locator('#wizard-next').click();
  const next = await page.locator('#wizard-next').boundingBox();
  assert.ok(next && next.y + next.height <= 690, 'Wizard footer must remain visible without scrolling.');
  const fail = route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ ok: false, error: '模拟失败：请重试' }) });
  await page.route('**/api/snapshot', fail);
  await page.locator('#wizard-refresh').click();
  await page.waitForFunction(() => document.getElementById('wizard-error').textContent.includes('模拟失败'));
  assert.equal(await page.locator('#wizard-refresh').isEnabled(), true);
  await page.unroute('**/api/snapshot', fail);
  await page.locator('#wizard-refresh').click();
  await page.waitForFunction(() => !document.getElementById('wizard-error').textContent);
  await page.locator('#wizard-next').click();
  await page.locator('#wizard-name').fill('重试后保存'); await page.locator('#wizard-id').fill('123123123');
  await page.locator('#wizard-next').click();
  await page.route('**/api/save', fail);
  await page.locator('#wizard-next').click();
  await page.waitForFunction(() => document.getElementById('wizard-error').textContent.includes('模拟失败'));
  assert.equal((await page.evaluate(() => window.remoteControl.snapshot())).value.devices.length, 0);
  assert.match(await page.locator('#wizard-peer-summary').textContent(), /重试后保存/);
  assert.equal(await page.locator('#wizard-next').isEnabled(), true);
  await fs.mkdir(path.join(__dirname, '../output/playwright'), { recursive: true });
  await page.screenshot({ path: path.join(__dirname, '../output/playwright/wizard-save-error-900.png') });
  await page.unroute('**/api/save', fail);
  await page.locator('#wizard-next').click();
  await page.waitForFunction(() => !document.getElementById('setup-dialog').open);
  assert.equal((await page.evaluate(() => window.remoteControl.snapshot())).value.devices.length, 1);
  assert.equal(await page.locator('#consent').isChecked(), false);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.screenshot({ path: path.join(__dirname, '../output/playwright/workspace-900.png'), fullPage: true });
  await page.setViewportSize({ width: 1200, height: 830 });
  await page.screenshot({ path: path.join(__dirname, '../output/playwright/workspace-after.png'), fullPage: true });
  console.log('PASS refresh error/retry, save error/retry with draft retained, no premature persistence, fresh consent and 900px layout.');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { await browser?.close(); });
